/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package USER;

import static admin.updateuser.mail;
import static admin.updateuser.usname;
import config.dbConnect;
import config.passwordHasher;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class updateinfor extends javax.swing.JFrame {
 

    /**
     * Creates new form updateinfor
     */
    
  
  String mail;
 
    
  public updateinfor(int id, String email, String contact, String password) {
        initComponents(); // Initialize the form components

        // Populate the text fields with the passed values
        idField.setText(String.valueOf(id)); // Set the idField
        emailField.setText(email);
        contactField.setText(contact);
        passwordField.setText(password);
        
         seepass2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // Toggle password visibility
                if (passwordField.getEchoChar() == '\0') {
                    // Hide the password
                    passwordField.setEchoChar('•'); // Default echo character for passwords
                    seepass.setText("Show Password");
                } else {
                    // Show the password
                    passwordField.setEchoChar('\0'); // Set echo char to null to show the password
                    seepass.setText("Hide Password");
                }
            }
        });
    }
  
  private void initComponentss() {
        // Initialize components (auto-generated by NetBeans)
        idField = new javax.swing.JTextField(); // Initialize idField
        emailField = new javax.swing.JTextField();
        contactField = new javax.swing.JTextField();
       

        // Add other initialization code here...
    }
public boolean dupcheck() {
    dbConnect db = new dbConnect();
    try {
        String query = "SELECT * FROM user WHERE u_email = ?";
        PreparedStatement pstmt = db.getConnection().prepareStatement(query);
        pstmt.setString(1, emailField.getText());
        ResultSet resultset = pstmt.executeQuery();

        if (resultset.next()) {
            mail = resultset.getString("u_email");
            if (mail.equals(emailField.getText())) {
                JOptionPane.showMessageDialog(null, "The email already exists",
                    "Error Registration", JOptionPane.ERROR_MESSAGE);
                emailField.setText("");
                return true;
            }
            return true;
        } else {
            return false;
        }
    } catch (SQLException ex) {
        System.out.println("" + ex);
        return false;
    }
}
  
  
    public boolean updatecheck(){
        
        dbConnect db = new dbConnect();
         
        try{
        String que = "SELECT * FROM user WHERE u_email='"+emailField.getText()+"' ";    
            ResultSet resultset = db.getData(que);
            if(resultset.next()){
                mail = resultset.getString("u_email");
            
                if(mail.equals(emailField.getText())){
                    
                    JOptionPane.showMessageDialog(null, "The email already existed",
                "Error Registration", JOptionPane.ERROR_MESSAGE);
                    emailField.setText("");
                    
                    return true;
                }
               
             return true;   
            }
            
            else {
                
                return false;
            }
        }catch(SQLException ex){
            System.out.println(""+ex);
            return false;
        }
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        contactField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        seepass = new javax.swing.JLabel();
        seepass2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        updateclick = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 192, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setForeground(new java.awt.Color(0, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contactField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        contactField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contactField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        contactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactFieldActionPerformed(evt);
            }
        });
        jPanel6.add(contactField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 310, 50));

        emailField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        emailField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        jPanel6.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 310, 50));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("ID:");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("Email:");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("Password:");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/backwardset.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 50, 40));

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setText("Contact:");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        idField.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        idField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });
        jPanel6.add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 310, 50));

        passwordField.setText("jPasswordField1");
        passwordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel6.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 260, 50));

        seepass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seepass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eyegamay.png"))); // NOI18N
        jPanel6.add(seepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 30, 30));

        seepass2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seepass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eyegamay.png"))); // NOI18N
        jPanel6.add(seepass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 30, 30));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 430, 410));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("USER");
        jLabel9.setToolTipText("");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 110, 30));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/personalinformation.png"))); // NOI18N
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 90));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("INFORMATION");
        jLabel10.setToolTipText("");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 300, 30));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 430, 100));

        updateclick.setBackground(new java.awt.Color(0, 102, 102));
        updateclick.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        updateclick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateclickMouseClicked(evt);
            }
        });
        updateclick.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("UPDATE INFORMATION");
        updateclick.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 30));

        jPanel3.add(updateclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 210, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void contactFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        employdash em = new employdash();
        em.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel20MouseClicked

    private void updateclickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateclickMouseClicked
       
        
        dbConnect db = new dbConnect();

        
        try{
       
String passwords = passwordHasher.hashPassword(passwordField.getText());


        if (emailField.getText().isEmpty() || contactField.getText().isEmpty() || passwordField.getText().isEmpty() ) {

            JOptionPane.showMessageDialog(null, "Invalid Registration: All fields are required.",
                "Error Registration", JOptionPane.ERROR_MESSAGE);
            return;
        } 
     else if (!emailField.getText().matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid email address (e.g., example@gmail.com).",
                "Error Registration", JOptionPane.ERROR_MESSAGE);
            return;

        } else if (passwordField.getText().length() < 8) {

            JOptionPane.showMessageDialog(null, "Password must be at least 8 characters long.",
                "Error Registration", JOptionPane.ERROR_MESSAGE);
            passwordField.setText("");
            return;
        }

        else if (!contactField.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Contact number must contain only digits.",
                "Error Registration", JOptionPane.ERROR_MESSAGE);
            return;
        }

        else if (contactField.getText().length() < 11 || contactField.getText().length() > 15) {
            JOptionPane.showMessageDialog(null, "Contact number must be between 11 and 15 digits.",
                "Error Registration", JOptionPane.ERROR_MESSAGE);
            contactField.setText("");
            return;
        }
        else if (updatecheck()){

            System.out.println("Duplicated Exist!");

        }
        else if (dupcheck()){
            
            System.out.println("Duplication Exist!");
        }

       
        else {
            db.updateData("UPDATE user SET u_email ='"+emailField.getText()+"',u_contact='"+contactField.getText()+"',u_password ='"+passwords+"' WHERE u_id ='"+idField.getText()+"'");

            JOptionPane.showMessageDialog(null, "Submitted Successfully");
        }
    
        }catch(NoSuchAlgorithmException ex){
        System.out.println(""+ex);
    }
    
        
        
    }//GEN-LAST:event_updateclickMouseClicked

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateinfor(0, "", "", "").setVisible(true); // Example usage
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField contactField;
    public javax.swing.JTextField emailField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel seepass;
    private javax.swing.JLabel seepass2;
    private javax.swing.JPanel updateclick;
    // End of variables declaration//GEN-END:variables
}
