/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.dbConnect;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Admin
 */
public class orderpage extends javax.swing.JFrame {

    /**
     * Creates new form orderpage
     */
    public orderpage() {
        initComponents();
        displayfood();
//        displaypersonal();
//        displayhouse();
//        displaysupplies();
    }
    
     Color logcolor = new Color(63,195,128);
    Color excolor = new Color(0,102,102);
//    private void customizeTableColumns(JTable food) {
//    food.getColumnModel().getColumn(0).setHeaderValue("Product Name");
//    food.getColumnModel().getColumn(1).setHeaderValue("Category");
//    food.getColumnModel().getColumn(2).setHeaderValue("Brand");
//    food.getColumnModel().getColumn(3).setHeaderValue("Price");
//    food.getColumnModel().getColumn(4).setHeaderValue("Stock");
//    food.getTableHeader().repaint(); // Refresh the header to show changes
//  
//}
            

    
    
    
    public void displayfood(){
    try{
        dbConnect dbc = new dbConnect();
        ResultSet rs = dbc.getData("SELECT p_id, p_name AS 'Product Name', p_brand AS 'Brand', p_price AS 'Price', p_stock AS 'Stock', p_category, p_image FROM product WHERE p_status = 'Available'");
        food.setModel(DbUtils.resultSetToTableModel(rs));
        rs.close();
    } catch(SQLException ex) {
        System.out.println("Errors: "+ex.getMessage());
    }
}
    
//     public void displaypersonal(){
//        try{
//            dbConnect dbc = new dbConnect();
//             ResultSet rs = dbc.getData("SELECT p_name AS 'Product Name', p_brand AS 'Brand', p_price AS 'Price', p_stock AS 'Stock' FROM product WHERE p_category = 'Personal Wellness' AND p_status = 'Available'");
//            personal.setModel(DbUtils.resultSetToTableModel(rs));
//             rs.close();
//        }catch(SQLException ex){
//            System.out.println("Errors: "+ex.getMessage());
//        
//        }
//        
//    }
//
//      public void displayhouse(){
//        try{
//            dbConnect dbc = new dbConnect();
//   ResultSet rs = dbc.getData("SELECT p_name AS 'Product Name', p_brand AS 'Brand', p_price AS 'Price', p_stock AS 'Stock' FROM product WHERE p_category = 'Household Essentials' AND p_status = 'Available'");
//            house.setModel(DbUtils.resultSetToTableModel(rs));
//             rs.close();
//        }catch(SQLException ex){
//            System.out.println("Errors: "+ex.getMessage());
//        
//        }
//        
//    }
//      
//       public void displaysupplies(){
//        try{
//            dbConnect dbc = new dbConnect();
//    ResultSet rs = dbc.getData("SELECT p_name AS 'Product Name', p_brand AS 'Brand', p_price AS 'Price', p_stock AS 'Stock' FROM product WHERE p_category = 'Supplies Utilities' AND p_status = 'Available'");
//            supplies.setModel(DbUtils.resultSetToTableModel(rs));
//             rs.close();
//        }catch(SQLException ex){
//            System.out.println("Errors: "+ex.getMessage());
//        
//        }
//        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        personal = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        food = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        supplies = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        house = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        VIEWORDER = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ADDORDER1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ADDORDER = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ADDORDER3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        personal.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        personal.setForeground(new java.awt.Color(0, 102, 102));
        personal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(personal);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 210));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 450, 230));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        food.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        food.setForeground(new java.awt.Color(0, 102, 102));
        food.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(food);

        jPanel10.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 210));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 450, 230));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("HOUSEHOLD ESSENTIALS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 250, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("SUPPLIES UTILITIES");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 210, 40));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supplies.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        supplies.setForeground(new java.awt.Color(0, 102, 102));
        supplies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(supplies);

        jPanel6.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 210));

        jPanel8.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 460, 230));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        house.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        house.setForeground(new java.awt.Color(0, 102, 102));
        house.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(house);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 210));

        jPanel8.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 460, 230));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("PERSONAL WELLNESS");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 230, 40));

        VIEWORDER.setBackground(new java.awt.Color(0, 102, 102));
        VIEWORDER.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        VIEWORDER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VIEWORDERMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VIEWORDERMouseExited(evt);
            }
        });
        VIEWORDER.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VIEW ORDER");
        VIEWORDER.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        ADDORDER1.setBackground(new java.awt.Color(0, 102, 102));
        ADDORDER1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ADDORDER1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADDORDER1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ADDORDER1MouseExited(evt);
            }
        });
        ADDORDER1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ADD ORDER");
        ADDORDER1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 20));

        VIEWORDER.add(ADDORDER1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 120, 40));

        jPanel8.add(VIEWORDER, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 130, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("FOOD BEVARAGE");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 40));

        ADDORDER.setBackground(new java.awt.Color(0, 102, 102));
        ADDORDER.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ADDORDER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDORDERMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADDORDERMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ADDORDERMouseExited(evt);
            }
        });
        ADDORDER.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ADD ORDER");
        ADDORDER.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        ADDORDER3.setBackground(new java.awt.Color(0, 102, 102));
        ADDORDER3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ADDORDER3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADDORDER3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ADDORDER3MouseExited(evt);
            }
        });
        ADDORDER3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ADD ORDER");
        ADDORDER3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 20));

        ADDORDER.add(ADDORDER3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 120, 40));

        jPanel8.add(ADDORDER, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, 130, 40));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 950, 610));

        jPanel11.setBackground(new java.awt.Color(0, 102, 102));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel11.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 390, 230));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/checkgamay.png"))); // NOI18N
        jPanel11.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 80, 80));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ORDER'S PAGE");
        jPanel11.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 410, -1));

        jPanel14.setBackground(new java.awt.Color(0, 102, 102));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
        });
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/images-removebg-preview.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel14.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        jPanel11.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 60));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  
    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
        // TODO add your handling code here:
        admindash order = new admindash();
       order.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jPanel14MouseClicked

    private void VIEWORDERMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VIEWORDERMouseEntered
        // TODO add your handling code here:
        
        VIEWORDER.setBackground(logcolor);
        
    }//GEN-LAST:event_VIEWORDERMouseEntered

    private void VIEWORDERMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VIEWORDERMouseExited
        // TODO add your handling code here:
        
         VIEWORDER.setBackground(excolor);
        
    }//GEN-LAST:event_VIEWORDERMouseExited

    private void ADDORDER1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDORDER1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDORDER1MouseEntered

    private void ADDORDER1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDORDER1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDORDER1MouseExited

    private void ADDORDER3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDORDER3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDORDER3MouseEntered

    private void ADDORDER3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDORDER3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDORDER3MouseExited

    private void ADDORDERMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDORDERMouseEntered
        // TODO add your handling code here:
        
           
       ADDORDER.setBackground(logcolor);
    }//GEN-LAST:event_ADDORDERMouseEntered

    private void ADDORDERMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDORDERMouseExited
        // TODO add your handling code here:
        
           
        ADDORDER.setBackground(excolor);
    }//GEN-LAST:event_ADDORDERMouseExited

    private void ADDORDERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDORDERMouseClicked
        // TODO add your handling code here:
        
         int rowfood =food.getSelectedRow();
      
         
                  
        if(rowfood<0){
            JOptionPane.showMessageDialog(null,"PLEASE SELECT AN ITEM");
            
        } else{
            
            try{
                dbConnect db = new dbConnect();
                TableModel fod = food.getModel();
                ResultSet rs = db.getData("SELECT * FROM product WHERE p_id = '"+fod.getValueAt(rowfood, 0)+"'");
                
                if(rs.next()){
                processpage pro = new processpage();
                
                pro.prodid.setText(""+rs.getInt("p_id"));
                pro.prodname.setText(""+rs.getString("p_name"));
                pro.prodprice.setText(""+rs.getFloat("p_price"));
                pro.prodbrand.setText(""+rs.getString("p_brand"));
                pro.prodstock.setText(""+rs.getInt("p_stock"));
                pro.prodcategory.setText(""+rs.getString("p_category"));
               pro.image.setIcon(pro.ResizeImage(rs.getString("p_image"),null,pro.image));
               pro.oldpath = rs.getString("p_image");
      pro.path = rs.getString("p_image");
      pro.destination=rs.getString("p_image");
             
               
                pro.setVisible(true);
                
                this.dispose();
                }   
            }catch(SQLException ex){
                
                System.out.println(""+ex);
            }
            
        }
        
//         int rowindex = usertable.getSelectedRow();
//        
//        if(rowindex<0){
//            JOptionPane.showMessageDialog(null,"PLEASE SELECT AN ITEM");
//            
//        } else{
//            
//        
//        try{
//        dbConnect db = new dbConnect();
//         TableModel tbl =  usertable.getModel();
//       ResultSet rs = db.getData("SELECT * FROM  user WHERE u_id = '"+tbl.getValueAt(rowindex, 0)+"'");
//      if(rs.next()){
//            updateuser up = new updateuser();
//          
//            up.uid.setText(""+rs.getInt("u_id"));
//            up.usernamere.setText(""+rs.getString("u_username"));
//       up.fname.setText(""+rs.getString("u_fname"));
//       up.lname.setText(""+rs.getString("u_lname"));
//       up.email.setText(""+rs.getString("u_email"));
//       up.contact.setText(""+rs.getString("u_contact"));
//       up.ty.setSelectedItem(""+rs.getString("u_type"));
//       up.oldpass.setText(""+rs.getString("u_password"));
//      up.status.setSelectedItem(""+rs.getString("u_stat"));
//      up.image.setIcon(up.ResizeImage(rs.getString("u_image"),null,up.image));
//      up.oldpath = rs.getString("u_image");
//      up.path = rs.getString("u_image");
//      up.destination=rs.getString("u_image");
//      up.setVisible(true);
//      
//      
//        this.dispose();
//       
//      }
//        }
//        
//        catch(SQLException ex){
//            System.out.println(""+ex);
//        } 
//        }
    }//GEN-LAST:event_ADDORDERMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(orderpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(orderpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(orderpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(orderpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new orderpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ADDORDER;
    private javax.swing.JPanel ADDORDER1;
    private javax.swing.JPanel ADDORDER3;
    private javax.swing.JPanel VIEWORDER;
    private javax.swing.JTable food;
    private javax.swing.JTable house;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable personal;
    private javax.swing.JTable supplies;
    // End of variables declaration//GEN-END:variables
}
