/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import USER.customerdashboard;
import USER.employdash;
import config.SessionClass;
import config.dbConnect;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import java.lang.String;
import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 *
 * @author Admin
 */
public class vieworder extends javax.swing.JFrame {

    /**
     * Creates new form vieworder
     */
public vieworder() {
        initComponents();
        displayAllOrders(); // Call the method to display only pending orders
        
          SearchButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String username =searchuser.getText().trim();
                if (!username.isEmpty()) {
                    searchUser(username);
                } else {
                    JOptionPane.showMessageDialog(vieworder.this, "Please enter a username.");
                }
            }
        });
        
    }



 private void logOrderUpdateAction(int userId, String username, int orderId) {
    String sql = "INSERT INTO logs (user_id, act, log_date) VALUES (?, ?, NOW())";

    dbConnect db = new dbConnect();
    try (Connection conn = db.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {

        pstmt.setInt(1, userId);
        pstmt.setString(2, "User (" + username + ") updated Order ID: " + orderId);
        pstmt.executeUpdate();

    } catch (SQLException e) {
        System.err.println("Failed to log order update action: " + e.getMessage());
    }
}

private int getCurrentUserId() {
    config.SessionClass ses = config.SessionClass.getInstance();
    return ses.getU_id();
}

private String getCurrentUsername() {
    config.SessionClass ses = config.SessionClass.getInstance();
    return ses.getUsername();
}



 private void searchUser(String username) {
        try {
            dbConnect dbc = new dbConnect();
            ResultSet rs = dbc.getData("SELECT s_id AS 'Order Id', u_id AS 'User Id', p_id AS 'Product Id', s_quantity AS 'Quantity', s_totalam AS 'Total Amount', s_cash AS 'Cash', s_change AS 'Change', s_status AS 'Status', s_date AS 'Date' FROM process WHERE u_id = '" + username + "'");
            vieworder.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
        } catch (SQLException ex) {
            System.out.println("Error: " + ex.getMessage());
            JOptionPane.showMessageDialog(this, "Error searching for user.");
        }
    }

  public void displayAllOrders() {
        try {
            dbConnect dbc = new dbConnect();
            ResultSet rs = dbc.getData("SELECT s_id AS 'Order ID', u_id AS 'User ID', p_id AS 'Product ID', s_quantity AS 'Quantity', s_totalam AS 'Total Amount', s_cash AS 'Cash Given', s_change AS 'Change Amount', s_status AS 'Order Status', s_date AS 'Order Date' FROM process ORDER BY s_id DESC");
            vieworder.setModel(DbUtils.resultSetToTableModel(rs)); // Assuming your JTable is named 'vieworder'
            rs.close();
        } catch (SQLException ex) {
            System.out.println("Errors: " + ex.getMessage());
            JOptionPane.showMessageDialog(this, "Error displaying data: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
Color logcolor = new Color(63,195,128);
    Color excolor = new Color(0,102,102);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vieworder = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        update = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        reset = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        searchuser = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("__________________________________________________________");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jPanel2.setForeground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vieworder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(vieworder);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 680, 380));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 700, 400));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 150, 10));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ORDERS OVERVIEW");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 390, -1));

        jPanel14.setBackground(new java.awt.Color(0, 102, 102));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel14MouseEntered(evt);
            }
        });
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/images-removebg-preview.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel14.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        jPanel3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 720, 100));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RECORDS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 240, 40));

        update.setBackground(new java.awt.Color(0, 102, 102));
        update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("UPDATE STATUS ");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        update.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 30));

        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 190, 50));

        reset.setBackground(new java.awt.Color(0, 102, 102));
        reset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resetMouseExited(evt);
            }
        });
        reset.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RESET");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        reset.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 110, 50));

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 102));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("ORDERS");
        jLabel21.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 140, 30));

        searchuser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        searchuser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchuser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        searchuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                searchuserMouseReleased(evt);
            }
        });
        searchuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchuserActionPerformed(evt);
            }
        });
        jPanel1.add(searchuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 250, 30));

        SearchButton.setBackground(new java.awt.Color(255, 255, 255));
        SearchButton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        SearchButton.setText("SEARCH");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:

        SessionClass session = SessionClass.getInstance();
        String userType = session.getType();

        if (userType != null) {

            if(userType.equals("Admin")){

                admindash adminDashboard = new admindash();
                adminDashboard.setVisible(true);

            }
            if(userType.equals("Customer")){
                customerdashboard customerDashboard = new customerdashboard(); // Replace with your actual customer dashboard class name
                customerDashboard.setVisible(true);

            }

            if(userType.equals("Employee")){

                employdash employeeDashboard = new employdash(); // Replace with your actual employee dashboard class name
                employeeDashboard.setVisible(true);

            }

            // Handle cases where the user type is not recognized

            // Optionally, you can redirect to a default dashboard or show an error message

            this.dispose();
        } else {
            // Handle the case where the session doesn't have user type information
            JOptionPane.showMessageDialog(null,"No account login first");
            this.dispose();
            // Optionally, show an error message
        }

    }//GEN-LAST:event_jLabel9MouseClicked

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
        // TODO add your handling code here:
        //        admindash order = new admindash();
        //       order.setVisible(true);
        //        this.dispose();

        SessionClass session = SessionClass.getInstance();
        String userType = session.getType();

        if (userType != null) {

            if(userType.equals("Admin")){

                admindash adminDashboard = new admindash();
                adminDashboard.setVisible(true);

            }
            if(userType.equals("Customer")){
                customerdashboard customerDashboard = new customerdashboard(); // Replace with your actual customer dashboard class name
                customerDashboard.setVisible(true);

            }

            if(userType.equals("Employee")){

                employdash employeeDashboard = new employdash(); // Replace with your actual employee dashboard class name
                employeeDashboard.setVisible(true);

            }

            // Handle cases where the user type is not recognized

            // Optionally, you can redirect to a default dashboard or show an error message

            this.dispose();
        } else {
            // Handle the case where the session doesn't have user type information
            JOptionPane.showMessageDialog(null,"No account login first");
            this.dispose();
            // Optionally, show an error message
        }

    }//GEN-LAST:event_jPanel14MouseClicked

    private void jPanel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel14MouseEntered

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:
        int rowindex = vieworder.getSelectedRow();
        SessionClass ses = SessionClass.getInstance();
        int orderIdStr = ses.getS_id();
        if (rowindex < 0) {
            JOptionPane.showMessageDialog(null, "PLEASE SELECT An ORDER");
            return; // Exit the method if no row is selected
        }

        // Assuming the s_id (order ID) is in the first column (index 0) of your vieworder table
        // **IMPORTANT: Adjust this index if s_id is in a different column.**
        int s_id_columnIndex = 0;
        int selected_s_id = (int) vieworder.getModel().getValueAt(rowindex, s_id_columnIndex);

        // **Assuming the 'Order Status' is in the 7th column (index 6). Adjust if it's different.**
        int s_status_table_columnIndex = 7;
        String currentStatusInTable = (String) vieworder.getModel().getValueAt(rowindex, s_status_table_columnIndex);

        if (!currentStatusInTable.equals("Pending")) {
            JOptionPane.showMessageDialog(null, "Only Pending orders can be updated.");
            return; // Exit the method if the order is not Pending
        }

        dbConnect db = new dbConnect();
        Connection con = db.getConnection();
        ResultSet rs = null;
        String currentStatusFromDB = null;

        try {
            String query = "SELECT s_status FROM process WHERE s_id = ?";
            PreparedStatement pstmt = con.prepareStatement(query);
            pstmt.setInt(1, selected_s_id);
            rs = pstmt.executeQuery();

            if (rs.next()) {
                currentStatusFromDB = rs.getString("s_status");

                if (currentStatusFromDB.equals("Pending")) {
                    // Update the status in the database to "Complete"
                    String updateQuery = "UPDATE process SET s_status = 'Complete' WHERE s_id = ?";
                    PreparedStatement updatePstmt = con.prepareStatement(updateQuery);
                    updatePstmt.setInt(1, selected_s_id);
                    int rowsAffected = updatePstmt.executeUpdate();

                    if (rowsAffected > 0) {
                        ses.setS_status("Complete"); // Update the session as well
                        // Optionally, update the table model to reflect the change immediately
                        if (s_status_table_columnIndex < vieworder.getColumnCount()) {
                            vieworder.getModel().setValueAt("Complete", rowindex, s_status_table_columnIndex);
                        }
                         int currentUserId = getCurrentUserId();
        String currentUsername = getCurrentUsername(); // Get the username
        // Log the order update action BEFORE updating the database
        logOrderUpdateAction(currentUserId, currentUsername, orderIdStr);
                        JOptionPane.showMessageDialog(null, "Order status updated to Complete.");
                    } else {
                        JOptionPane.showMessageDialog(null, "Failed to update order status.");
                    }
                    updatePstmt.close();
                } else if (currentStatusFromDB.equals("Complete")) {
                    JOptionPane.showMessageDialog(null, "Order status is already Complete.");
                } else {
                    JOptionPane.showMessageDialog(null, "Order status is not Pending and cannot be updated.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Could not find order with ID: " + selected_s_id);
            }

            pstmt.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage());
            ex.printStackTrace();
        } finally {
            try {
                if (rs != null) rs.close();
                if (con != null) con.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_updateMouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        
        update.setBackground(logcolor);
        
    }//GEN-LAST:event_jLabel4MouseEntered

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        // TODO add your handling code here:
        
            update.setBackground(logcolor);
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        // TODO add your handling code here:
        
            update.setBackground(excolor);
        
    }//GEN-LAST:event_updateMouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        
        reset.setBackground(logcolor);
        
    }//GEN-LAST:event_jLabel5MouseEntered

    private void resetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseEntered
        // TODO add your handling code here:
         reset.setBackground(logcolor);
        
    }//GEN-LAST:event_resetMouseEntered

    private void resetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseExited
        // TODO add your handling code here:
        
          reset.setBackground(excolor);
        
    }//GEN-LAST:event_resetMouseExited

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        // TODO add your handling code here:
        
        displayAllOrders();
        
    }//GEN-LAST:event_resetMouseClicked

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
            update.setBackground(excolor);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
             int rowindex = vieworder.getSelectedRow();
        SessionClass ses = SessionClass.getInstance();

        if (rowindex < 0) {
            JOptionPane.showMessageDialog(null, "PLEASE SELECT An ORDER");
            return; // Exit the method if no row is selected
        }

        // Assuming the s_id (order ID) is in the first column (index 0) of your vieworder table
        // **IMPORTANT: Adjust this index if s_id is in a different column.**
        int s_id_columnIndex = 0;
        int selected_s_id = (int) vieworder.getModel().getValueAt(rowindex, s_id_columnIndex);

        // **Assuming the 'Order Status' is in the 7th column (index 6). Adjust if it's different.**
        int s_status_table_columnIndex = 7;
        String currentStatusInTable = (String) vieworder.getModel().getValueAt(rowindex, s_status_table_columnIndex);

        if (!currentStatusInTable.equals("Pending")) {
            JOptionPane.showMessageDialog(null, "Only Pending orders can be updated.");
            return; // Exit the method if the order is not Pending
        }

        dbConnect db = new dbConnect();
        Connection con = db.getConnection();
        ResultSet rs = null;
        String currentStatusFromDB = null;

        try {
            String query = "SELECT s_status FROM process WHERE s_id = ?";
            PreparedStatement pstmt = con.prepareStatement(query);
            pstmt.setInt(1, selected_s_id);
            rs = pstmt.executeQuery();

            if (rs.next()) {
                currentStatusFromDB = rs.getString("s_status");

                if (currentStatusFromDB.equals("Pending")) {
                    // Update the status in the database to "Complete"
                    String updateQuery = "UPDATE process SET s_status = 'Complete' WHERE s_id = ?";
                    PreparedStatement updatePstmt = con.prepareStatement(updateQuery);
                    updatePstmt.setInt(1, selected_s_id);
                    int rowsAffected = updatePstmt.executeUpdate();

                    if (rowsAffected > 0) {
                        ses.setS_status("Complete"); // Update the session as well
                        // Optionally, update the table model to reflect the change immediately
                        if (s_status_table_columnIndex < vieworder.getColumnCount()) {
                            vieworder.getModel().setValueAt("Complete", rowindex, s_status_table_columnIndex);
                        }
                        JOptionPane.showMessageDialog(null, "Order status updated to Complete.");
                    } else {
                        JOptionPane.showMessageDialog(null, "Failed to update order status.");
                    }
                    updatePstmt.close();
                } else if (currentStatusFromDB.equals("Complete")) {
                    JOptionPane.showMessageDialog(null, "Order status is already Complete.");
                } else {
                    JOptionPane.showMessageDialog(null, "Order status is not Pending and cannot be updated.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Could not find order with ID: " + selected_s_id);
            }

            pstmt.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage());
            ex.printStackTrace();
        } finally {
            try {
                if (rs != null) rs.close();
                if (con != null) con.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
        
        reset.setBackground(excolor);
        
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        
           displayAllOrders();
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void searchuserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchuserMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_searchuserMouseReleased

    private void searchuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchuserActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vieworder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vieworder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vieworder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vieworder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vieworder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel reset;
    private javax.swing.JTextField searchuser;
    private javax.swing.JPanel update;
    private javax.swing.JTable vieworder;
    // End of variables declaration//GEN-END:variables
}
